### ISSUE TITLE
The Segmented Training Dataset 

### ISSUE THREAD

**Issue by ayamaa8** [iamrosmarin/BSc_Thesis_Skin_Lesion_Detection#1]
I'm trying to use some of the helpful data and information provided here.

I'm trying to use the segmented dataset, however only the segmented testing data is there on the Github project under isbi-segmented-dataset. Where can I find the segmented dataset for training as well please? As I wasn't able to find it.

If it is not on your Github project page, can you please provide the segmented training dataset?

**Comment by adriaromero** [comment]
For this project I used the data provided by the [ISIC Challenge in 2016](https://challenge.kitware.com/#challenge/560d7856cad3a57cfde481ba). I also recommend you to take a look at this year's challenge: https://challenge2018.isic-archive.com/

**Comment by ayamaa8** [comment]
I see. The segmented testing images are posted here in your project (Under utils\matlab_create_segemented_img\isbi-segmented-dataset\ **segmented_test** ).

However, the segmented training  images are not here, so when I was trying to segment the training images using the Matlab code you provided here  ('create_segmented_img_from_mask.m') to get the segmented training images from the masks on the ISIC Challenge 2016, I don't get the segmented training output images. 

So I wanted to know if the segmented training images can be provided here, or if I can obtain them from the same Matlab code provided here.

The Matlab code gives me an error that the img variable is not defined even though it is (using imread and the correct directories).
