### ISSUE TITLE
How do I find the data for this code or a reference data for skin lesions with masks?

### ISSUE THREAD

**Issue by arash1409** [iamrosmarin/BSc_Thesis_Skin_Lesion_Detection#3]

**Comment by adriaromero** [comment]
@arash1409 you might want to take a look at https://challenge2019.isic-archive.com/ challenge, where the organizers provide segmentation and classification datasets. Good luck!

**Comment by arash1409** [comment]
> @arash1409 you might want to take a look at https://challenge2019.isic-archive.com/ challenge, where the organizers provide segmentation and classification datasets. Good luck!

tnX, but this data dose not have binary mask for segmentation!

**Comment by adriaromero** [comment]
@arash1409 sorry, it looks this year is not including segmentation tasks. Take a look at the 2018 Challenge, where they did include segmentation: https://challenge2018.isic-archive.com/task1/

**Comment by arash1409** [comment]
> @arash1409 sorry, it looks this year is not including segmentation tasks. Take a look at the 2018 Challenge, where they did include segmentation: https://challenge2018.isic-archive.com/task1/

tnQ
